### ISSUE TITLE
[Progress Tracker] BREW-352 - Kibbles Crafting System

### ISSUE THREAD

**Issue by cadowtin** [TheGiddyLimit/homebrew#1509]
Created this issue for me to track my own progress on Kibbles Crafting System.

**Initial Adding stuff Pass**

- [x] Crafting
  - [x] Why do you need Crafting?
  - [x] Who can craft?
  - [x] What can I craft?
  - [x] A Player-Driven System
    - [x] Working with your GM
  - [x] Hooking Your Players In5

**Comment by revilowaldow** [comment]
For what it's worth after taking a closer look at your initial file I think I'll probably be reworking most of it. 
Happy to follow behind you if you'd rather get content out faster but I think I'm pretty keen to try and bump up the quality.
I don't tend to do releases in stages until it's all done though so if you need the content faster I'd say keep going.

**Comment by revilowaldow** [comment]
You can see some initial work in this PR.
Note the greatly increased tagging, including across files to load Kibble's other works where referred to.
Image additions, the breakout of reference content like tables etc. 
I've also fixed a number of typos, I'm obviously a bit slower than you'll be but just an indication of the sort of thing I'm working towards. 
Pretty sure I'll be doing the items a bit differently too as `baseitem`s that can then be modified and grouped etc with custom item properties and types
https://github.com/TheGiddyLimit/homebrew/pull/1510

**Comment by cadowtin** [comment]
Cool, yeah I assumed there was a way to group the items, but was unsure how to so I kind of did the best with what I saw available. I ended up taking a break on the brew atm, as I had worked on parts up to where players were using.
Will make updates as I get time, as I think having it fully complete would be nice. As for tagging, nice I was intending to go back over the document at the end and apply tagging, but have it applied now is nice.

Planning to do some work on it today, and perhaps in the coming days

**Comment by revilowaldow** [comment]
There's been a lot more progress since that initial PR I tagged.
It's complete with the exception of the items themselves that I'll be making my way through.
I'll likely be done in a week or two and coordinating on the generic variant strategy is unlikely to work effectively so happy to just finish it off on my side.
![image](https://user-images.githubusercontent.com/52298102/205463637-8b325a8f-88fd-4399-b79f-2604f158cfdc.png)

**Comment by cadowtin** [comment]
Sounds good,  I'll just go through and validate some of the tables, as the method I was using to copy data made a few mistakes

**Comment by cadowtin** [comment]
**Checking/fixing my formatting errors**
- [ ] Formatting checking
- [ ] Cover Page & Credits
- [ ] Crafting
- [ ] Crafting Time
- [ ] Materials
- [ ] Type of Materials
- [ ] Purchasing Tables by Type
- [ ] Purchasing Tables by Rarity
- [ ] Harvesting & Looting
- [ ] Loot
- [ ] Gathering Tables
- [ ] Alchemy
- [ ] Poisoncraft
- [ ] Blacksmithing
- [ ] Cooking
- [ ] Enchanting
- [ ] Scrollscribing
- [ ] Wand Whittling
- [ ] Leatherworking
- [ ] Tinkering
- [ ] Woodcarving
- [ ] Runecarving
- [ ] Engineering
- [ ] Minor Branches
- [ ] App. A: Calculating New Items
- [ ] App. B: Optional Detailed Names
- [ ] App. C: Variant Rules
- [ ] App. E: Exotic Materials
- [ ] App. F: Camp Actions
- [ ] App. M: Crafting Magic & Items
- [ ] Crafting Sheet
- [ ] License
